### ISSUE TITLE
Obtaining BUID

### ISSUE THREAD

**Issue by redmondWC** [lakecountypassage/WazeTravelTimesPoller#1]
It looks like Waze updated website so JSON file does not display BUID in the address bar anymore. Is there another way to obtain this or does it look different and not 18 character alpha-numeric string anymore?

**Comment by lakecountypassage** [comment]
Missed this comment earlier. The new method was added to the README back in Februrary 2023.

https://github.com/lakecountypassage/WazeTravelTimesPoller/blob/master/README.md#geting-the-waze-uid
